[package]
name = "tanktics-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
rendering = []

[dependencies]
interfaces = { path = "../interfaces" }
zipper = { path = "../../zipper" }
zipper_derive = { path = "../../zipper/zipper_derive" }
