[package]
name = "tanktics-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
rendering = ["interfaces/preview"]

[dependencies]
rustc-hash = "1.1"
interfaces = { path = "../interfaces" }
zipper = { path = "../../zipper", features = ["debug"] }
zipper_derive = { path = "../../zipper/zipper_derive" }
semver = "1.0"
csv = "1.3"
num-rational = { version = "0.4", features = ["serde"] }
rhai = { version = "1.19", default-features = false, features = ["std", "sync", "only_i32", "no_float", "no_custom_syntax"] }
