[package]
name = "tanktics-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
rendering = []

[dependencies]
rustc-hash = "1.1"
interfaces = { path = "../interfaces" }
zipper = { path = "../../zipper", features = ["debug"] }
zipper_derive = { path = "../../zipper/zipper_derive" }
semver = "1.0"
csv = "1.3"
num-rational = { version = "0.4", features = ["serde"] }
